server:
  port: 8060


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: HOSPITALS-ON-PANEL
          uri: lb://HOSPITALS-ON-PANEL
          predicates:
            - Path=/hospitals/**
        - id: TREATMENT-SERVICE
          uri: lb://TREATMENT-SERVICE
          predicates:
            - Path=/appointment/**
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
